In [ ]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [ ]:
df= pd.read_csv("/content/email.csv")

In [ ]:
df.head(10)

text  target
0  From ilug-admin@linux.ie Mon Jul 29 11:28:02 2...       0
1  From gort44@excite.com Mon Jun 24 17:54:21 200...       1
2  From fork-admin@xent.com Mon Jul 29 11:39:57 2...       1
3  From dcm123@btamail.net.cn Mon Jun 24 17:49:23...       1
4  From ilug-admin@linux.ie Mon Aug 19 11:02:47 2...       0
5  From tobaccodemon@terra.es Sat Sep 7 22:05:58 ...       1
6  From larlar78@MailOps.Com Sat Jun 30 00:19:08 ...       1
7  From rpm-list-admin@freshrpms.net Thu Jul 25 1...       0
8  From exmh-users-admin@redhat.com Wed Aug 7 06:...       0
9  From contractor@goldenbay.com.cy Tue Jul 23 23...       1

In [ ]:

df.shape

(5796, 2)

In [ ]:
df.columns

Index(['text', 'target'], dtype='object')

In [ ]:
df.drop_duplicates(inplace=True)
print(df.shape)

(5329, 2)


In [ ]:
print(df.isnull().sum())

text      0
target    0
dtype: int64


In [ ]:
# download the stopwords package
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def process(text):
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)

    clean = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    return clean
# to show the tokenization
df['text'].head().apply(process)

0    [ilugadminlinuxie, Mon, Jul, 29, 112802, 2002,...
1    [gort44excitecom, Mon, Jun, 24, 175421, 2002, ...
2    [forkadminxentcom, Mon, Jul, 29, 113957, 2002,...
3    [dcm123btamailnetcn, Mon, Jun, 24, 174923, 200...
4    [ilugadminlinuxie, Mon, Aug, 19, 110247, 2002,...
Name: text, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
message = CountVectorizer(analyzer=process).fit_transform(df['text'])

In [ ]:
#split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(message, df['target'], test_size=0.20, random_state=0)
# To see the shape of the data
print(message.shape)

(5329, 192304)


In [ ]:
# create and train the Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(xtrain, ytrain)

In [ ]:
print(classifier.predict(xtrain))
print(ytrain.values)

[1 0 1 ... 0 0 0]
[1 0 1 ... 0 0 0]


In [ ]:
# Evaluating the model on the training data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(xtrain)
print(classification_report(ytrain, pred))
print()
print("Confusion Matrix: \n", confusion_matrix(ytrain, pred))
print("Accuracy: \n", accuracy_score(ytrain, pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      2889
           1       1.00      0.96      0.98      1374

    accuracy                           0.99      4263
   macro avg       0.99      0.98      0.99      4263
weighted avg       0.99      0.99      0.99      4263


Confusion Matrix: 
 [[2889    0]
 [  51 1323]]
Accuracy: 
 0.988036593947924


In [ ]:
#print the predictions
print(classifier.predict(xtest))
#print the actual values
print(ytest.values)

[0 0 0 ... 1 0 1]
[0 0 0 ... 1 0 1]


In [ ]:
# Evaluating the model on the training data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(xtest)
print(classification_report(ytest, pred))
print()
print("Confusion Matrix: \n", confusion_matrix(ytest, pred))
print("Accuracy: \n", accuracy_score(ytest, pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       749
           1       1.00      0.93      0.96       317

    accuracy                           0.98      1066
   macro avg       0.99      0.97      0.97      1066
weighted avg       0.98      0.98      0.98      1066


Confusion Matrix: 
 [[749   0]
 [ 22 295]]
Accuracy: 
 0.9793621013133208
